
swagger: '2.0'
info:
  title: pub-api
  description: Project about API gateways
  version: 1.0.0
host: pub-api-gateway-8yny0kuq.ew.gateway.dev
schemes:
  - https
produces:
  - application/json
paths:
  /index:
    get:
      summary: Shows a static website form a cloud storage bucket
      operationId: staticindex
      produces:
        - text/html; charset=utf-8
      x-google-backend:
        address: https://storage.googleapis.com/apiprojekti/publicstaticwebsite/index.html
      responses:
        '200':
          description: Displays the html page
          schema:
            type: string

  /pub/{name_of_the_pub}:    
    get:
      parameters:
        - in: path
          name: name_of_the_pub
          required: true
          type: string
          minimum: 1
          description: The name of the pub
      summary: Get satellite-results for a pub
      operationId: satpub
      x-google-backend:
        address: https://us-central1-week9-2-323806.cloudfunctions.net/get_satellites_poc 
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /pubday/{name_of_the_pub}:    
    get:
      parameters:
        - in: path
          name: name_of_the_pub
          required: true
          type: string
          minimum: 1
          description: The name of the pub
      summary: Get satellite-results for a pub in one day
      operationId: satpubforday
      x-google-backend:
        address: https://us-central1-week9-2-323806.cloudfunctions.net/get_satellites_poc-1-days
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /find:
    post:
      summary: Gives a name of a brewery that is close to the given coordinates
      operationId: findpub
      x-google-backend:
        address: https://europe-west2-week9-2-323806.cloudfunctions.net/closestfinder
      responses:
        '200':
          description: No errors
          schema:
            type: string
