CREATE DATABASE pubs;

CREATE TABLE names (id VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, street VARCHAR(255), city VARCHAR(255), longitude DOUBLE PRECISION NOT NULL, latitude DOUBLE PRECISION NOT NULL);